version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    # ローカルのコード変更をコンテナに反映させる（ホットリロード用）
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/my_app_db
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "n6uO1+J8xgVqkrc9t2b7F1w0as8Hd4y2pEq1rK3oU2Q="
    depends_on:
      - db
    command: sh -c "npm install && npm run dev:with-migrate"

  db:
    image: postgres:16-alpine
    container_name: my-next-app-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_app_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  node_modules:
  db_data:
